### ISSUE TITLE
Database query Issue

### ISSUE THREAD

**Issue by DeepanshuGOYAL05** [DeepanshuGOYAL05/Techademics#2]
I am facing an issue for creating  an table which will autoincrement value from start index if you delete any data from middle in table

**Comment by zainulhasan** [comment]
Anybody working on this issue ?

**Comment by zainulhasan** [comment]
> from

I want to work on this issue. I need a little bit more detail before I can start. 

Thanks

**Comment by DeepanshuGOYAL05** [comment]
Hi,

Can you work on another feature required in this?

**Comment by chandresh1339** [comment]
Yes, I can work on another feature if you would like.

**Comment by DeepanshuGOYAL05** [comment]
Hi,

Yes you can solve this issue!!

**Comment by DeepanshuGOYAL05** [comment]
Hi,

You can work on the issue that i have reported now.

**Comment by chandresh1339** [comment]
@DeepanshuGOYAL05 ,Please check the PR for the issue: Database query Issue #2. Thanks

**Comment by codelikesuraj** [comment]
Hi, I don't really understand this issue, could you explain better please
