### ISSUE TITLE
Contact us and About page 

### ISSUE THREAD

**Issue by DeepanshuGOYAL05** [DeepanshuGOYAL05/Techademics#4]
Contact us and About page are not working in student and Teacher Portal.

**Comment by JunaidJaved248** [comment]
@DeepanshuGOYAL05 I want to contribute, can you please elaborate issue

**Comment by pajardsaputra** [comment]
I already fix it , give me access to push and PR

**Comment by DeepanshuGOYAL05** [comment]
When you login in student and teacher portal...when you click on about
us..it is not redirecting to that page. Are you able to relate it?

**Comment by DeepanshuGOYAL05** [comment]
> I already fix it , give me access to push and PR

Okay, Let me see

**Comment by KevinMathewTh** [comment]
Hey i just made a PR , Please review it thank you

**Comment by DeepanshuGOYAL05** [comment]
> I already fix it , give me access to push and PR

There is not any open pull request

**Comment by KevinMathewTh** [comment]
Hey, is this issue still open?

**Comment by DeepanshuGOYAL05** [comment]
> Hey i just made a PR , Please review it thank you



> Hey, is this issue still open?

No it was fixed, Thank you!!
