### ISSUE TITLE
Teacher Registration

### ISSUE THREAD

**Issue by DeepanshuGOYAL05** [DeepanshuGOYAL05/Techademics#6]
When someone register as a teacher, it should have a teacher id provided my database admin so that only he/she can register as a teacher

**Comment by meashishjha** [comment]
Hi,

Please explain more about this and i can resolve this issue.

**Comment by DeepanshuGOYAL05** [comment]
Hi,

When you go in register tab. If you select Teacher from select account
part, there should be a mandatory field which should ask about teacher id
which should be given by database admin to verify it as a valid teacher and
register him/her

**Comment by meashishjha** [comment]
The ids should be automatically generated from database once the teacher registers, right? There is already a autoincrement ID field in the database which assigns unique id to teacher.

Do you want additional ids for teacher hich can be setup by admin?

**Comment by DeepanshuGOYAL05** [comment]
No, it is generating id but my issue is that for now any one is able to
register as a teacher but it shouldn't be . So for this a db admin should
provide a unique key to each teacher so that he/she can be verified at time
of registration as a teacher

**Comment by KevinMathewTh** [comment]
Could you confirm if my understanding is correct
You want a new input field when the user selects to register as teacher
and this input field should check if the key provided is the same as the one provided by the admin

One query i have is , is the key unique for each teacher or is it a common key for all teacher registration

**Comment by KevinMathewTh** [comment]
PS: is this issue an hacktober fest issue?

**Comment by DeepanshuGOYAL05** [comment]
This key will unique for each teacher

**Comment by DeepanshuGOYAL05** [comment]
Yes this is Hacktoberfest issue

**Comment by DeepanshuGOYAL05** [comment]
> The ids should be automatically generated from database once the teacher registers, right? There is already a autoincrement ID field in the database which assigns unique id to teacher.
> 
> Do you want additional ids for teacher hich can be setup by admin?

Hey, are you doing this?
